// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWsxiN507QAHFl6K0nCAXr4DbPre2CXw',
    appId: '1:956143562877:web:faaf9a7f375d20d9124114',
    messagingSenderId: '956143562877',
    projectId: 'untitled4-44637',
    authDomain: 'untitled4-44637.firebaseapp.com',
    storageBucket: 'untitled4-44637.appspot.com',
    measurementId: 'G-Y60FPDB998',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMiPwXngqgFRIOPb8U6-5Ba5ndwR6k7So',
    appId: '1:956143562877:android:aafa4d3b82023cac124114',
    messagingSenderId: '956143562877',
    projectId: 'untitled4-44637',
    storageBucket: 'untitled4-44637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5X2eRakXYqOMlZ3kWncNyb0ZaSs_9iqM',
    appId: '1:956143562877:ios:683d1111d2f9f92e124114',
    messagingSenderId: '956143562877',
    projectId: 'untitled4-44637',
    storageBucket: 'untitled4-44637.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5X2eRakXYqOMlZ3kWncNyb0ZaSs_9iqM',
    appId: '1:956143562877:ios:c128a657e737e1a0124114',
    messagingSenderId: '956143562877',
    projectId: 'untitled4-44637',
    storageBucket: 'untitled4-44637.appspot.com',
    iosBundleId: 'com.example.untitled4.RunnerTests',
  );
}
